# fly.toml app configuration file generated for remove-bg-little-sky-9855 on 2024-10-16T21:55:22+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'remove-bg-little-sky-9855'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 10000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  CORS_UI_ORIGIN = 'https://remove-bg-ui.vercel.app'